name: Publish Docker image
# Docker Hub にコンテナを公開する
# 参考： https://docs.github.com/ja/actions/publishing-packages/publishing-docker-images

# 条件：何等かのタグが打たれた場合
# 参考： https://docs.github.com/ja/actions/using-workflows/triggering-a-workflow
on:
  push:
    tags:
    - '*'

# 処理
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      # packages: write
      # コンテナの管理は Docker Hub であり、Github Package での管理は行わない想定でコメントアウト。
      contents: read
      # attestations: write
      # 構成情報は不要のためコメントアウト。後述。
    steps:
      - name: Check out the repo
        # using action https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        # using action https://github.com/docker/login-action
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Extract metadata (tags, labels) for Docker
      #   # using action https://github.com/docker/metadata-action
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: my-docker-hub-namespace/my-docker-hub-repository
      # タグ shogosugano/mobamura-tool:latest、ラベル無しで固定のため、コメントアウト

      - name: Build and push Docker image
        # using action https://github.com/docker/build-push-action
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          # tags: ${{ steps.meta.outputs.tags }}
          tags: shogosugano/mobamura-tool:latest
          # labels: ${{ steps.meta.outputs.labels }}

      # - name: Generate artifact attestation
      #   # using action https://github.com/actions/attest-build-provenance
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
      # コンテナレベルでの流用を期待しないアプリであり構成情報は不要のためコメントアウト。
      # 参考： https://docs.github.com/ja/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds